### ISSUE TITLE
About the Dataset

### ISSUE THREAD

**Issue by Marc565** [user1342/DroidDetective#4]
Author Hi, can you share the dataset you used? Thank you very much.

**Comment by user1342** [comment]
Hi @Marc565, thanks for your interest in DroidDetective! The dataset used is mentioned in the [Readme](https://github.com/user1342/DroidDetective). It's the Android malware dataset from @ashishb here: https://github.com/ashishb/android-malware. For the 'known-good' dataset, I believe these were apps taken from a stock Pixel device. Hope this helps.

Cheers.

**Comment by user1342** [comment]
Hi @Marc565, thanks for your interest in DroidDetective! The dataset used is mentioned in the [Readme](https://github.com/user1342/DroidDetective). It's the Android malware dataset from @ashishb here: https://github.com/ashishb/android-malware. For the 'known-good' dataset, I believe these were apps taken from a stock Pixel device. Hope this helps.

Cheers.

**Comment by user1342** [comment]
Hi @Marc565, thanks for your interest in DroidDetective! The dataset used is mentioned in the [Readme](https://github.com/user1342/DroidDetective). It's the Android malware dataset from @ashishb here: https://github.com/ashishb/android-malware. For the 'known-good' dataset, I believe these were apps taken from a stock Pixel device. Hope this helps.

Cheers.
